services:
  - type: web
    name: pramod-portfolio-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  - type: static
    name: pramod-portfolio
    buildCommand: npm install --prefix client && npm run build --prefix client
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        sync: false